[package]
name = "triducal/roblox-template"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2.0.0" # Module Loader For Services/Controllers
Charm = "littensy/charm@0.8.0" # State Management
CharmSync = "littensy/charm-sync@0.1.0" # Server-Client Sync
CharmVide = "littensy/vide-charm@0.1.0" # Vide Hooks
Remo = "littensy/remo@1.5.0" # Typed Remotes
Ripple = "littensy/ripple@0.9.1" # Motion Library
Sift = "csqrl/sift@0.0.9" # Immutable Data Manipulation
Vide = "centau/vide@0.3.1" # UI Library
Lapis = "nezuo/lapis@0.3.3" # Datastore Library
MockDataStore = "buildthomas/mockdatastoreservice@1.0.3" # Mock Datastore For Testing
Promise = "evaera/promise@4.0.0" # Promise
t = "osyrisrblx/t@3.1.1" # Runtime type-checking
